from selenium.webdriver.common.by import By

FROM_FIELD = (By.ID, 'from')
TO_FIELD = (By.ID, 'to')
REQUEST_TAXI_BUTTON = (By.XPATH, "//button[text() = 'Pedir un taxi']")
MODE_COMFORT_BUTTON = (By.XPATH, "//div[contains(@class, 'tcard') and .//div[text()='Comfort']]")
TELEPHONE_NUMBER_FIELD = (By.ID, 'phone')
TELEPHONE_BUTTON = (By.XPATH, '//div[@class = "np-button"]')
ADD_CARD_BUTTON = (By.XPATH, "//div[contains(@class, 'pp-button') and .//div[text()='Método de pago']]")
CVV_INPUT = (By.CSS_SELECTOR, "input#code.card-input")
CARD_INPUT = (By.ID, 'number')
MESSAGE_INPUT = (By.ID, 'comment')
BLANKET_TISSUES_CHECKBOX = (By.XPATH, "//div[contains(text(),'Manta')]/..//input[@type='checkbox']")
ICE_CREAM_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]')
DRIVER_MODAL = (By.CLASS_NAME, 'card-input')
SMS_CODE_FIELD = (By.ID, "code")
SMS_CONFIRM_BUTTON = (By.XPATH, "//button[contains(text(), 'Confirmar')]")
NEXT_BUTTON = (By.CSS_SELECTOR, "button[type='submit']")
CARD_OPTION = (By.XPATH, "//div[contains(@class, 'pp-row')]//div[text()='Agregar tarjeta']")
CARD_ADD_BUTTON = (By.XPATH, "//button[contains(., 'Agregar')]")
PAYMENT_CLOSE_BUTTON = (By.CSS_SELECTOR, "div.payment-picker.open button.close-button.section-close")
PAYMENT_PICKER = (By.CSS_SELECTOR, "div.payment-picker.open")
DRIVER_INFO = (By.CLASS_NAME, "order-body")